window.MIMI21_FISH=[
['M21-01','the-original','THE ORIGINAL','CORE / IDENTITY','><)))0>','pilot'],
['M21-02','quiet-fish','QUIET FISH','CORE / IDENTITY','><)))•>','ready'],
['M21-03','the-twenty-one','THE TWENTY-ONE','CORE / IDENTITY','><)))21>','ready'],
['M21-04','birthday-only-fish','BIRTHDAY-ONLY FISH','CORE / IDENTITY','*><)))21>*','ready'],
['M21-05','confirmed','CONFIRMED','EVERYDAY CONVERSATION','><)))✓>','ready'],
['M21-06','question-fish','QUESTION FISH','EVERYDAY CONVERSATION','><)))?>','ready'],
['M21-07','processing-fish','PROCESSING FISH','EVERYDAY CONVERSATION','><)))…>','ready'],
['M21-08','side-eye-fish','SIDE-EYE FISH','EVERYDAY CONVERSATION','><)))¬>','ready'],
['M21-09','more-fish','MORE FISH','EVERYDAY CONVERSATION','><)))+>','ready'],
['M21-10','reduced-capacity-fish','REDUCED-CAPACITY FISH','COOKED / FUNNY / USEFUL','><)))%>','ready'],
['M21-11','internet-fish','INTERNET FISH','COOKED / FUNNY / USEFUL','><)))@>','ready'],
['M21-12','dead-fully-done-fish','DEAD / FULLY-DONE FISH','COOKED / FUNNY / USEFUL','><)))×>','ready'],
['M21-13','wobble-fish','WOBBLE FISH','COOKED / FUNNY / USEFUL','><)))0>~','ready'],
['M21-14','what-is-happening-fish','WHAT-IS-HAPPENING FISH','COOKED / FUNNY / USEFUL','><)))0>???','ready'],
['M21-15','everything-fish','EVERYTHING FISH','COOKED / FUNNY / USEFUL','><)))0>!!!','ready'],
['M21-16','reboot-fish','REBOOT FISH','COOKED / FUNNY / USEFUL','><)))0>↺','ready'],
['M21-17','love-fish','LOVE FISH','LOVE / CARE / HOME','><)))♡>','pilot'],
['M21-18','thinking-of-you-fish','THINKING-OF-YOU FISH','LOVE / CARE / HOME','><)))0>⋯♡','ready'],
['M21-19','proud-win-fish','PROUD / WIN FISH','LOVE / CARE / HOME','><)))0>✦','ready'],
['M21-20','got-you-fish','GOT-YOU FISH','LOVE / CARE / HOME','><)))0>☂','ready'],
['M21-21','home-fish','HOME FISH','LOVE / CARE / HOME','><)))0>⌂','ready'],
['M21-22','hug-whisper-fish','HUG / WHISPER FISH','LOVE / CARE / HOME','(><)))0>)','ready'],
['M21-23','no-words-fish','NO-WORDS FISH','LOVE / CARE / HOME','><)))0>—♡','ready'],
['M21-24','not-going-anywhere-keep-going-not-goodbye','NOT-GOING-ANYWHERE FISH','LOVE / CARE / HOME','><)))0>∞','ready'],
['M21-25','good-track-fish','GOOD-TRACK FISH','MUSIC / CREATIVE','><)))0>♪','pilot'],
['M21-26','re-room-fish','RE-ROOM FISH','MUSIC / CREATIVE','><)))0>≈','ready'],
['M21-27','groove-fish','GROOVE FISH','MUSIC / CREATIVE','><)))0>∿','ready'],
['M21-28','strange-good-fish','STRANGE-GOOD FISH','MUSIC / CREATIVE','><)))0>※','ready'],
['M21-29','twenty-one-activated','TWENTY-ONE ACTIVATED','BIRTHDAY / SPECIAL','><)))21>!','ready'],
['M21-30','mimi-code','MIMI CODE','BIRTHDAY / SPECIAL','><)))0>/21','ready']
];
